- name: Allow OpenSSH rule
  ufw:
    rule: allow
    name: OpenSSH
    src: "{{ item }}"
  with_items: "{{ ip_whitelist }}"
  become: yes

- name: Allow http rules local
  ufw:
    rule: "allow"
    port: "80"
    proto: "tcp"
    src: "{{ item }}"
  with_items: "{{ ip_whitelist }}"
  become: yes

- name: Allow web rules local
  ufw:
    rule: "allow"
    port: "443"
    proto: "tcp"
    src: "{{ item }}"
  with_items: "{{ ip_whitelist }}"
  become: yes

- name: Deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny
    logging: "on"
  become: yes