- name: Installation for Ubuntu Server
  include_tasks: install_ub.yml
  when: distro=="ub"

- name: Installation for Opensuse Leap
  include_tasks: install_leap.yml
  when: distro=="leap"

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable service docker
  systemd:
    name: docker
    enabled: yes
  become: yes

- name: Load docker on boot
  systemd:
    state: started
    name: docker
  become: yes